// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVleBE5MYDONeerKAALyEFCbhOkW9MT6w',
    appId: '1:677336048242:web:c63042e91f4f9dbc7098eb',
    messagingSenderId: '677336048242',
    projectId: 'brisketnv',
    authDomain: 'brisketnv.firebaseapp.com',
    storageBucket: 'brisketnv.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXqxvmr-r_ycUAtLCqrTztFZksfhLmCbo',
    appId: '1:677336048242:android:a4c0e8e96135526b7098eb',
    messagingSenderId: '677336048242',
    projectId: 'brisketnv',
    storageBucket: 'brisketnv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    // apiKey: 'AIzaSyDGUSLgxx2JHOtbzRJuHPmRC2UFR4lbN6w',
    apiKey: 'AIzaSyCXqxvmr-r_ycUAtLCqrTztFZksfhLmCbo',
    appId: '1:677336048242:ios:631e7f6d38054e207098eb',
    messagingSenderId: '677336048242',
    projectId: 'brisketnv',
    storageBucket: 'brisketnv.appspot.com',
    iosClientId: '677336048242-docf2s2settrsc0qpv6r5u5f4ef8tssn.apps.googleusercontent.com',
    iosBundleId: 'com.example.briskitnv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    // apiKey: 'AIzaSyDGUSLgxx2JHOtbzRJuHPmRC2UFR4lbN6w',
    apiKey: 'AIzaSyCXqxvmr-r_ycUAtLCqrTztFZksfhLmCbo',
    appId: '1:677336048242:ios:631e7f6d38054e207098eb',
    messagingSenderId: '677336048242',
    projectId: 'brisketnv',
    storageBucket: 'brisketnv.appspot.com',
    iosClientId: '677336048242-docf2s2settrsc0qpv6r5u5f4ef8tssn.apps.googleusercontent.com',
    iosBundleId: 'com.example.briskitnv',
  );
}
